baseURL: "https://rust.christina-quast.de/"
title: "Linux kernel programming blog"
languageCode: "en-us"
theme: "hugo-xmin"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "post/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 4
    - name: About
      url: "about/"
      weight: 5
    - name: Workshops
      url: "workshops/"
      weight: 6

params:
  description: "A blog on Rust, Linux Kernel Development and related tech stuff."
  footer: "&copy; [Christina Quast](https://chrysh.github.io) 2024 -- {Year} | [Github](https://github.com/chrysh)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
